[tool.poetry]
name = "bank-widget-clean"
version = "0.1.0"
description = ""
authors = ["You <you@example.com>"]
readme = "README.md"
package-mode = false



[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
pytest = "~8.0.0"
flake8 = "^7.0.0"
mypy = "^1.8.0"
black = "^24.0.0"
isort = "^5.13.0"

[tool.black]
line-length = 119
target-version = ["py39"]

[tool.isort]
profile = "black"
line-length = 119