[tool.poetry]
name = "bank-widget-clean"
version = "0.1.0"
description = "Bank widget project"
authors = ["mariakhusainova9@gmail.com"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.0"
openpyxl = "^3.1.0"
python-dotenv = "^1.0.1"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
mypy = "^1.14.0"
isort = "^9.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry-core.masonry.api"
